apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $k, $v := .Values.sealedSecret.encryptedData }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "myapp.fullname" . }}-secret
      labels:
        {{- include "myapp.labels" . | nindent 8 }}
    type: Opaque
