fullnameOverride: monitoring

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 6h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 600Mi

grafana:
  adminPassword: admin      
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

alertmanager:
  enabled: true
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
